
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA-URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: book-service
            uri: lb://book-service
            predicates:
              - Path=/api/v1/book/**
          - id: library-service
            uri: lb://library-service
            predicates:
              - Path=/api/v1/library/**

    discovery:
      enabled: true

